version: 1.0


phases:
  pre_build:
    commands:
    - echo Configuring environment...
    - COMMIT_HASH=${echo $CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-8}
    - TIME_STAMP=${date +%Y.%m%d.%H%M}

    - echo Configuring application
    - echo TODO

  build:
    commands:

  post_build:
    commands:  