meridian:
  version: v1
  address: localhost:8088
  apollo: localhost:8083
  db:
    - 127.0.0.1:2379
  cache: something 
  instrument:
    address: 0.0.0.0:4222
    stopic: collector
    collect: 15s
    location: logs/